stages:
  - build
  - test
  - deploy


.build:
  stage: build
  script:
    - '& "$env:NUGET_PATH" restore -PackagesDirectory ".\packages" -DisableParallelProcessing -Recursive -configfile "C:\gitlab-runner\NuGet\newNuGet.config"'  # restore Nuget dependencies
    - '& "$env:MSBUILD_PATH" /p:Configuration=$BuildConfiguration'  # build the project
    - New-Item -ItemType Directory -Force -Path $Deploydir
    - Copy-Item -path $ArtifactDir\* -Exclude ("*.config","appsettings.json","appsettings.Development.json")  -destination $Deploydir -recurse -force   
    
.deploy:
  stage: deploy
  script:
    - Invoke-Command -ComputerName $Url -ScriptBlock {C:\CARTA\StopStartService\StopService.ps1 -serviceName $args[0] -processType $args[1]} -ArgumentList  $serviceName,$servicetype
    - "robocopy /S /E /DCOPY:DA /COPY:DAT /R:10 /W:30 /B /XO $Sourcedeploy $Destinationdeploy  ; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }"
    - Invoke-Command -ComputerName $Url -ScriptBlock {C:\CARTA\StopStartService\StartService.ps1 -serviceName $args[0] -processType $args[1]} -ArgumentList $serviceName,$servicetype

.clean_deploy:
  stage: deploy
  script:
    - Remove-Item -LiteralPath "$CI_BUILDS_DIR/$CI_COMMIT_BRANCH$CI_PROJECT_ID/deploy$CI_PIPELINE_ID" -Force -Recurse

################################################  master pipe  ##################################### 
build_master:
  extends: .build
  only :
   refs :
      - master


deploy_prod:
  extends: .deploy
  when: manual
  only:
    refs:
      - master
  environment:
    name: prod
    url: $Url  

clean_deploy_file_prod:
  extends: .clean_deploy
  needs:
    - deploy_prod
  only:
    refs:
      - master


#****************************staging

build_staging:
  extends: .build
  only :
   refs :
      - master-Staging

deploy_staging:
  extends: .deploy
  only:
    refs:
      - master-Staging
  environment:
    name: staging
    url: $Url  

clean_deploy_file_staging:
  extends: .clean_deploy
  needs:
    - deploy_staging
  only:
    refs:
      - master-Staging

#******************************** NewUat
build_newuat:
  extends: .build
  only :
   refs :
      - master-newUat

deploy_newuat:
  extends: .deploy
  only:
    refs:
      - master-newUat
  environment:
    name: New_uat
    url: $Url  


clean_deploy_file_newuat:
  extends: .clean_deploy
  needs:
    - deploy_newuat
  only:
    refs:
      - master-newUat


#******************************** uat
build_uat:
  extends: .build
  only :
   refs :
      - master-uat
  

deploy_uat:
  extends: .deploy
  only:
    refs:
      - master-uat  
  environment:
    name: uat
    url: $Url  


clean_deploy_file_uat:
  extends: .clean_deploy
  needs:
    - deploy_uat
  only:
    refs:
      - master-uat 


include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

code_quality:
  stage:  test
  tags:
    - code
  rules:
    - if: $CI_COMMIT_BRANCH == "master-newUat" || $CI_COMMIT_BRANCH == "master-uat" || $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]   

semgrep-sast:
  tags:
    - code 
  rules:
    - if: $CI_COMMIT_BRANCH == "master-newUat" || $CI_COMMIT_BRANCH == "master-uat" || $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: test

