stages:
  - release
  - build
  - test
  - aftertest
  - deploy
  - regression_test

.build_MERGE:
  stage: test
  script:
    - $env:JAVA_HOME = "C:\Program Files\Java\jdk-17"
    - $env:PATH = "C:\Program Files\Java\jdk-17\bin;$env:PATH"
    - '& "$env:NUGET_PATH" restore -PackagesDirectory ".\packages" -DisableParallelProcessing -Recursive -configfile "C:\gitlab-runner\NuGet\newNuGet.config"' # restore Nuget dependencies
    - SonarScanner.MSBuild.exe begin /k:"$CI_PROJECT_NAME" /d:sonar.host.url=$sonarHostUrl /d:sonar.login="$sonarLogin" /d:sonar.password=$sonarPass
    - '& "$env:MSBUILD_PATH" /p:Configuration=$BuildConfiguration' # build the project
    - SonarScanner.MSBuild.exe end /d:sonar.login="$sonarLogin" /d:sonar.password=$sonarPass


.build:
  stage: build
  script:
    - '& "$env:NUGET_PATH" restore -PackagesDirectory ".\packages" -DisableParallelProcessing -Recursive -configfile "C:\gitlab-runner\NuGet\newNuGet.config"'  # restore Nuget dependencies
    - '& "$env:MSBUILD_PATH" /p:Configuration=$BuildConfiguration' 
    - '& "$env:MSBUILD_PATH" .\$webAppFolder /p:DeployOnBuild=true  /p:PublishProfile="$PublishProfile"'
    - New-Item -ItemType Directory -Force -Path $Deploydir
    - Copy-Item -path $ArtifactDir\* -Exclude ("*.config","appsettings.json","appsettings.Development.json")  -destination $Deploydir -recurse -force  


.deploy:
  stage: deploy
  script:
    - "robocopy /S /E /DCOPY:DA /COPY:DAT /R:10 /W:30 /B /XO $Sourcedeploy $Destinationdeploy  ; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }"

.clean_deploy:
  stage: deploy
  script:
    - Remove-Item -LiteralPath "$Deploydir" -Force -Recurse


.create release:
  stage: release
  script: 
    - $lastTag = git describe --tags (git rev-list --tags --max-count=1)
    - echo $lastTag
    - $feature_index= $lastTag.Split('.')[1]
    - $cr_index= $lastTag.Split('.')[2]
    - $defect_index= $lastTag.Split('.')[3]       

    - $task_type = $CI_COMMIT_TITLE.Split('-')[3]
    - echo $task_type
    - if ($task_type -eq "DF") { $defect_index = [int]$defect_index + 1 }
    - |
      if ($task_type -eq "FT") { 
        $defect_index = '0'
        $cr_index = '0' 
        $feature_index = [int]$feature_index + 1 
        }
    - |
      if ($task_type -eq "CR") { 
        $defect_index = '0'  
        $cr_index = [int]$cr_index + 1
         }
    
    - echo $feature_index
    - echo $cr_index
    - echo $defect_index
    - $newTag = "master-V.$feature_index.$cr_index.$defect_index"
    - |
      if ($task_type -ne "CR" -and $task_type -ne "DF" -and $task_type -ne "FT" ) { 
        $hot_change= $lastTag.Split('.')[4]
        if ($hot_change -eq $null ){
           $hot_change = '0'
        } 
        $hot_change = [int]$hot_change + 1
        $newTag = "master-V.$feature_index.$cr_index.$defect_index.$hot_change"
         }
    - echo $newTag
    - 'C:\gitlab-runner\Release-CLI\bin\release-cli.exe create  --description "descr" -tag-name $newTag --ref "$CI_COMMIT_SHA"'


################################################  master pipe  ##################################### 
include:
- template: Security/SAST.gitlab-ci.yml


semgrep-sast:
  rules:
    - if:  $CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
   - code
  stage: test

packages-version-update:
  stage: aftertest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
  script:
    - echo $CI_PROJECT_PATH
    - '& $env:NUGET_PATH restore -PackagesDirectory ".\packages" -DisableParallelProcessing -Recursive -configfile "C:\gitlab-runner\NuGet\newNuGet.config" '# restore Nuget dependencies
    - C:\gitlab-runner\mrs2.ps1 -SourceFolderPath ".\" -CI_PROJECT_PATH $CI_PROJECT_PATH

owasp-job:
  script:
    - C:\gitlab-runner\owasp.ps1 -GIT_CLONE_PATH $GIT_CLONE_PATH -CI_PROJECT_ID $CI_PROJECT_ID -CI_PROJECT_NAME $CI_PROJECT_NAME
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
  artifacts:
    when: on_success
    paths:
      - report*.html
      
create_release_master:
  extends : .create release
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'

build_master:
  extends: .build
  only :
   refs :
      - tags


deploy_prod:
  extends: .deploy
  when: manual
  only:
    refs:
      - tags
  environment:
    name: prod
    url: $Url  

clean_deploy_file_prod:
  extends: .clean_deploy
  needs:
    - deploy_uat
  only:
    refs:
      - tags


#********************************
build_uat:
  extends: .build
  only :
   refs :
      - master-uat 

deploy_uat:
  extends: .deploy
  only:
    refs:
      - master-uat  
  environment:
    name: uat
    url: $Url  
    


clean_deploy_file_uat:
  extends: .clean_deploy
  needs:
    - deploy_uat
  only:
    refs:
      - master-uat 



code_quality:
  extends: 
    - .build_MERGE
  rules:
    - if:  $CI_PIPELINE_SOURCE == "merge_request_event"  



