//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.External.Dal.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARTA_UK_V3Entities : DbContext
    {
        public CARTA_UK_V3Entities()
            : base("name=CARTA_UK_V3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V3_API_EXTERNAL_SERVICE_PARAMS> V3_API_EXTERNAL_SERVICE_PARAMS { get; set; }
        public virtual DbSet<V3_EXTERNAL_BRANCH_API_LOGINS> V3_EXTERNAL_BRANCH_API_LOGINS { get; set; }
        public virtual DbSet<V3_EXTERNAL_ENDPOINTS> V3_EXTERNAL_ENDPOINTS { get; set; }
        public virtual DbSet<V3_API_EXTERNAL_SERVICE> V3_API_EXTERNAL_SERVICE { get; set; }
    }
}
