//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class V3_API_LOGIN_ENDPOINTS
    {
        public int BRANCH_API_LOGIN_UID { get; set; }
        public string SERVICE_ID { get; set; }
        public string ENDPOINT { get; set; }
        public string WRRAPED_VALUE { get; set; }
        public string CONCERNED_ENTITY { get; set; }
    }
}
