//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class V3_API_EXTERNAL_SERVICE_PARAMS
    {
        public int UID { get; set; }
        public string EXTERNAL_SERVICE_NAME { get; set; }
        public string PARAMS_NAME { get; set; }
        public string PARAMS_TO_SEND { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public Nullable<bool> IS_INPUT { get; set; }
        public Nullable<bool> IS_SENSITIVE { get; set; }
        public string KEY_ALGORITHM { get; set; }
        public string KEY_INDEX { get; set; }
        public string SERVICE_ID { get; set; }
        public Nullable<int> PROC_ID { get; set; }
        public Nullable<int> ORDINAL { get; set; }
        public string FIELD_FORMAT_TYPE { get; set; }
        public string FIELD_FORMAT { get; set; }
    }
}
