//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class V3_EXTERNAL_BRANCH_API_LOGINS
    {
        public int UID { get; set; }
        public string INSTITUTION_ID { get; set; }
        public string BRANCH_ID { get; set; }
        public string LOGIN { get; set; }
        public string PASS { get; set; }
        public string CHANNEL_TYPE { get; set; }
        public string CHANNEL_ID { get; set; }
        public string SERVICE_ID { get; set; }
        public Nullable<bool> JWE_ENABLED { get; set; }
        public string JWE_ALGORITHM { get; set; }
        public string KEY_INDEX { get; set; }
    }
}
