//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class V3_EXTERNAL_ENDPOINTS
    {
        public string ENDPOINT_ID { get; set; }
        public string ENDPOINT { get; set; }
        public string LOGIN { get; set; }
        public string PASS { get; set; }
        public string CHANNEL_TYPE { get; set; }
        public string CHANNEL_ID { get; set; }
        public string OPTIONAL_FIELD_1 { get; set; }
        public string OPTIONAL_FIELD_2 { get; set; }
    }
}
