//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.Api.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class APATHA_CARD_TOKENS
    {
        public string CLIENT_ID { get; set; }
        public string CARD_TOKEN { get; set; }
        public bool STATUS_CODE { get; set; }
        public Nullable<System.DateTime> STATUS_DATE { get; set; }
    }
}
