//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.Api.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.THIRD_PARTY_OPERATIONS = new HashSet<THIRD_PARTY_OPERATIONS>();
        }
    
        public string INSTITUTION_ID { get; set; }
        public string BRANCH_ID { get; set; }
        public string CLIENT_ID { get; set; }
        public int CARD_PROGRAM_ID { get; set; }
        public int CLIENT_PROFILE_ID { get; set; }
        public Nullable<int> CLIENT_STATUS { get; set; }
        public string PRIMARY_CLIENT_ID { get; set; }
        public string RELATIONSHIP { get; set; }
        public string ALIAS { get; set; }
        public string STATUS_CARD { get; set; }
        public string CARD_LAST_4_DIGITS { get; set; }
        public int PIN_RETRIEVE_ATTEMPTS { get; set; }
        public Nullable<decimal> BALANCE_LOW { get; set; }
        public decimal BALANCE { get; set; }
        public Nullable<System.DateTime> BALANCE_DATE { get; set; }
        public string CARD_PROGRAM_LIMIT_TYPE { get; set; }
        public int ACTIVATION_ATTEMPTS { get; set; }
        public bool BALANCE_CHANGED { get; set; }
        public string STATUS_CARD_MODIFIER_ID { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFICATION_DATE { get; set; }
        public string MODIFIED_BY_CLIENT { get; set; }
        public Nullable<System.DateTime> DATE_LAST_CARD_STATUS_UPDATE { get; set; }
        public int RENEW_STATUS { get; set; }
        public Nullable<System.DateTime> ACTIVATION_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<int> IS_AUTO_SUSPENDED { get; set; }
        public Nullable<bool> ISDELIVRED { get; set; }
        public string SHADOW_ACCOUNT_NBR { get; set; }
        public string CUSTOMER_STATUS_CODE { get; set; }
        public string CUSTOMER_STATUS_REASON { get; set; }
        public string CEASE_ALL { get; set; }
        public string THIRD_PARTY_ENROLLEMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THIRD_PARTY_OPERATIONS> THIRD_PARTY_OPERATIONS { get; set; }
    }
}
