//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.Api.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIRD_PARTY_OPERATIONS
    {
        public string INTERNAL_PAYMENT_ID { get; set; }
        public string EXTERNAL_PAYMENT_ID { get; set; }
        public string INSTITUTION_ID { get; set; }
        public string BRANCH_ID { get; set; }
        public string CLIENT_ID { get; set; }
        public string TRACKING_ACCOUNT { get; set; }
        public string SOURCE_ACCOUNT { get; set; }
        public string DESTINATION_ACCOUNT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string INITIAL_REFERENCE { get; set; }
        public string PROCESSING_REFERENCE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONFIRMATION_REFERENCE { get; set; }
        public string TRACKING_MICROFILM_NUMBER { get; set; }
        public string CLIENT_MICROFILM_NUMBER { get; set; }
        public string CONFIRMATION_MICROFILM_NUMBER { get; set; }
        public string OPERATION_TYPE { get; set; }
        public string FINAL_EXECUTION_STATUS { get; set; }
        public System.DateTime OPERATION_START_DATE { get; set; }
        public Nullable<System.DateTime> OPERATION_END_DATE { get; set; }
        public string OPERATION_STATUS { get; set; }
        public string OPERATION_STATUS_LABEL { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
    }
}
