//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.Api.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class V3_API_EXTERNAL_SERVICE
    {
        public int UID { get; set; }
        public string SERVICE_GTW_ID { get; set; }
        public string SERVICE_GTW_NAME { get; set; }
        public string EXTERNAL_SERVICE_NAME { get; set; }
        public string REQUEST_MAP { get; set; }
        public string CRITERIA { get; set; }
        public string HEADERS { get; set; }
    }
}
