//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carta.Api.External.Dal.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class V3_CARD_PROGRAM_APATHA_ENROLLMENT
    {
        public string INSTITUTION_ID { get; set; }
        public string BRANCH_ID { get; set; }
        public int CARD_PROGRAM_ID { get; set; }
        public Nullable<bool> IS_ENABLED { get; set; }
        public string FINANCIAL_INSTITUTION_ID { get; set; }
        public string ORGANISATION_ID { get; set; }
        public string API_KEY { get; set; }
        public string CHALLENGE_METHOD { get; set; }
    }
}
